# Generated by Django 3.2.12 on 2022-03-13 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('banner_image', models.URLField(blank=True, max_length=300, null=True)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('legal', models.TextField(blank=True, null=True)),
                ('url', models.URLField(editable=False, max_length=300, null=True)),
                ('event_key', models.CharField(editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.TextField(blank=True, help_text='Display text next to field', null=True)),
                ('required', models.BooleanField(default=True, help_text='Require user input')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.eventfieldtype')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_fields',
            field=models.ManyToManyField(to='sample.EventField'),
        ),
    ]
